# Database connection configuration
#   You will have to edit this section according to your database setup
#   Note: plugin was tested on MariaDB (MySQL)
database:
  # Connector URL
  #   example:     jdbc:       mysql      ://localhost: 3306 /  MineAuction
  #   explanation: jdbc:<type of database>://<address>:<port>/<database name>
  #     <type of database> We suggest using mysql
  #     <address> If your database is not on local machine, change this
  #     <port> Common database port is 3306
  #     <database name> The name of your database
  url: 'jdbc:mysql://localhost:3306/MineAuction'
  # Connection user (database login)
  #   AVOID using the user 'root' if you can - preferably make one user
  #         for MineAuction only, with access to MineAuction's tables only
  user: 'mineauction'
  # Connection (database) password
  password: ''
  # Prefix of all table names. Usefull to distinguish 
  prefix: 'ma_'

# ---------------------------------------------------------------------------- #
# Plugin's options
options:
  general:
    # Check for updates automatically
    checkVersion: true
    # Enable verbose (debug) logging to console
    verboseLogging: false
    
  signs:
    # You can disable all MineAuction's sign functions
    # to speed up the plugin a little if you don't use them.
    enable: true
    
    # Sign text configuration - changes the appearance of MineAuction signs
    #
    # Please note that these changes apply to NEWLY CREATED SIGNS ONLY. In order
    # to "recreate" the old signs, you have to run a command <command> @fixme
    #
    # Every sign is split in two parts - First two lines are the same throughout
    # the whole plugin - they are the "header". The other two lines are
    # type-specific, so you can distinct between the different sign types
    #
    # You can freely use colors in the signs' texts - both magic characters
    # ('&' and '§') are accepted.
    #
    # Please note that it is important to use the correct amount of lines - 
    # even if they are empty, they have to be present in config. It is also
    # better to enclose the lines in quotes.
    signTexts:
      # First two lines of the sign - the header
      header:
        - ''
        - '§8[§4Auction§8]'
      # The other two lines (3rd and 4th) for each type of sign
      types:
        deposit:
          - '§6    DEPOSIT'
          - ''
        withdraw:
          - '§6   WITHDRAW'
          - ''